package com.example.data.remote

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Base64
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.net.URL
import javax.net.ssl.HttpsURLConnection

class GeminiApiService {

    private fun getApiKey(apiKeyOverride: String?): String {
        if (!apiKeyOverride.isNullOrBlank()) return apiKeyOverride.trim()
        return try {
            val field = BuildConfig::class.java.getField("GEMINI_API_KEY")
            field.get(null)?.toString()?.trim() ?: ""
        } catch (ignored: Exception) {
            ""
        }
    }

    suspend fun generateContent(
        prompt: String,
        apiKeyOverride: String? = null
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val apiKey = getApiKey(apiKeyOverride)

            if (apiKey.isBlank() || apiKey == "your_gemini_api_key_here") {
                return@withContext Result.failure(
                    IllegalStateException("Gemini API Key is not configured. Please set GEMINI_API_KEY in .env file.")
                )
            }

            val endpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$apiKey"
            val url = URL(endpoint)

            val payload = JSONObject().apply {
                val contents = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val parts = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", prompt)
                            }
                            put(partObj)
                        }
                        put("parts", parts)
                    }
                    put(contentObj)
                }
                put("contents", contents)
            }

            val conn = (url.openConnection() as HttpsURLConnection).apply {
                requestMethod = "POST"
                connectTimeout = 30_000
                readTimeout = 30_000
                doOutput = true
                setRequestProperty("Content-Type", "application/json")
            }

            conn.outputStream.use { os ->
                os.write(payload.toString().toByteArray(Charsets.UTF_8))
            }

            val responseCode = conn.responseCode
            val responseStream = if (responseCode in 200..299) conn.inputStream else conn.errorStream
            val responseText = responseStream.bufferedReader().use { it.readText() }

            if (responseCode != 200) {
                val safeMsg = parseErrorMessage(responseText, responseCode)
                return@withContext Result.failure(IllegalStateException(safeMsg))
            }

            val textResult = parseGeminiResponse(responseText)
            if (textResult.isNullOrBlank()) {
                return@withContext Result.failure(IllegalStateException("No response generated by AI model."))
            }

            Result.success(textResult)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun describeImage(
        context: Context,
        imageUri: Uri,
        prompt: String = "Describe this photo in detail for a gallery app. Include visual details, objects, setting, colors, and key elements in 2-3 concise sentences.",
        apiKeyOverride: String? = null
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val apiKey = getApiKey(apiKeyOverride)

            if (apiKey.isBlank() || apiKey == "your_gemini_api_key_here") {
                return@withContext Result.failure(
                    IllegalStateException("Gemini API Key is not configured. Please set GEMINI_API_KEY in .env file.")
                )
            }

            val base64Image = encodeImageToBase64(context, imageUri)
                ?: return@withContext Result.failure(IllegalStateException("Unable to read or encode image for AI analysis."))

            val endpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$apiKey"
            val url = URL(endpoint)

            val payload = JSONObject().apply {
                val contents = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val parts = JSONArray().apply {
                            val textPart = JSONObject().apply {
                                put("text", prompt)
                            }
                            val imagePart = JSONObject().apply {
                                val inlineData = JSONObject().apply {
                                    put("mime_type", "image/jpeg")
                                    put("data", base64Image)
                                }
                                put("inline_data", inlineData)
                            }
                            put(textPart)
                            put(imagePart)
                        }
                        put("parts", parts)
                    }
                    put(contentObj)
                }
                put("contents", contents)
            }

            val conn = (url.openConnection() as HttpsURLConnection).apply {
                requestMethod = "POST"
                connectTimeout = 30_000
                readTimeout = 30_000
                doOutput = true
                setRequestProperty("Content-Type", "application/json")
            }

            conn.outputStream.use { os ->
                os.write(payload.toString().toByteArray(Charsets.UTF_8))
            }

            val responseCode = conn.responseCode
            val responseStream = if (responseCode in 200..299) conn.inputStream else conn.errorStream
            val responseText = responseStream.bufferedReader().use { it.readText() }

            if (responseCode != 200) {
                val safeMsg = parseErrorMessage(responseText, responseCode)
                return@withContext Result.failure(IllegalStateException(safeMsg))
            }

            val textResult = parseGeminiResponse(responseText)
            if (textResult.isNullOrBlank()) {
                return@withContext Result.failure(IllegalStateException("No AI caption generated."))
            }

            Result.success(textResult)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun parseGeminiResponse(responseText: String): String? {
        return try {
            val json = JSONObject(responseText)
            val candidates = json.optJSONArray("candidates") ?: return null
            if (candidates.length() == 0) return null
            val firstCandidate = candidates.getJSONObject(0)
            val content = firstCandidate.optJSONObject("content") ?: return null
            val parts = content.optJSONArray("parts") ?: return null
            if (parts.length() == 0) return null
            val textBuilder = StringBuilder()
            for (i in 0 until parts.length()) {
                val part = parts.getJSONObject(i)
                textBuilder.append(part.optString("text", ""))
            }
            textBuilder.toString().trim()
        } catch (e: Exception) {
            null
        }
    }

    private fun parseErrorMessage(responseText: String, code: Int): String {
        return try {
            val json = JSONObject(responseText)
            val errorObj = json.optJSONObject("error")
            val msg = errorObj?.optString("message") ?: "HTTP Error $code"
            when {
                code == 400 && msg.contains("API_KEY_INVALID", ignoreCase = true) ->
                    "Invalid API key provided. Please check GEMINI_API_KEY in .env."
                code == 403 -> "API key authorization error ($msg)."
                code == 429 -> "Rate limit exceeded. Please try again in a moment."
                else -> msg
            }
        } catch (e: Exception) {
            "API error (HTTP $code)"
        }
    }

    private fun encodeImageToBase64(context: Context, imageUri: Uri): String? {
        return try {
            val inputStream: InputStream = context.contentResolver.openInputStream(imageUri) ?: return null
            val originalBitmap = BitmapFactory.decodeStream(inputStream) ?: return null
            inputStream.close()

            val maxDimension = 1024
            val scaledBitmap = if (originalBitmap.width > maxDimension || originalBitmap.height > maxDimension) {
                val ratio = originalBitmap.width.toFloat() / originalBitmap.height.toFloat()
                val targetW = if (ratio >= 1) maxDimension else (maxDimension * ratio).toInt()
                val targetH = if (ratio < 1) maxDimension else (maxDimension / ratio).toInt()
                Bitmap.createScaledBitmap(originalBitmap, targetW, targetH, true)
            } else {
                originalBitmap
            }

            val baos = ByteArrayOutputStream()
            scaledBitmap.compress(Bitmap.CompressFormat.JPEG, 85, baos)
            val byteArray = baos.toByteArray()
            Base64.encodeToString(byteArray, Base64.NO_WRAP)
        } catch (e: Exception) {
            null
        }
    }
}
